DROP DATABASE IF EXISTS ecomerce;
CREATE DATABASE ecomerce;
USE ecomerce;
CREATE TABLE produit(
    id INT AUTO_INCREMENT,
    imag VARCHAR(255),
    price VARCHAR(255),
    quantity VARCHAR(255),
    designation VARCHAR(255),
    title VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
    PRIMARY KEY(id)
);
